services:
  metabase:
    build:
      context: .
      dockerfile: metabase/Dockerfile
    container_name: metabase
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
    ports:
      - "${MB_PORT:-3000}:3000"
    volumes:
      - ./data/prod:/data:ro
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: ${MB_DB_USER}
    ports:
      - "${MB_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${MB_DB_USER}
      POSTGRES_DB: ${MB_DB_DBNAME}
      POSTGRES_PASSWORD: ${MB_DB_PASS}
    volumes:
      - ./metabase/pg_data:/var/lib/postgresql/data
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge
