rnic_dbt:
  outputs:
    dev:
      type: duckdb
      path: /home/chris/rnic-copro-analytics/data/prod/dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: /home/chris/rnic-copro-analytics/data/prod/prod.duckdb
      threads: 4

  target: dev
